username:
  description: "[g]luware username."
  type: "string"
  required: true
password:
  description: "[g]luware user password."
  type: "string"
  secret: true
  required: true
base_url:
  description: "[g]luware Base url (https://glups01.gluware.lab)"
  type: "string"
  secret: false
  required: true
org_id:
  description: "[g]luware Org ID"
  type: "string"
  secret: false
  required: true  