username:
  description: "Gluware username."
  type: "string"
  required: true
password:
  description: "Gluware user password."
  type: "string"
  secret: true
  required: true
base_url:
  description: "Gluware Base url (https://glups01.gluware.lab)"
  type: "string"
  secret: false
  required: true
org_id:
  description: "Gluware Org ID"
  type: "string"
  secret: false
  required: true  