---
name: "json_webhook"
pack: "gluware"
description: "Rule to handle JSON payloads received via webhook."
trigger:
  type: "core.st2.webhook"
criteria: {}
action:
  ref: "gluware.save_json_to_disk"
  parameters:
    payload: "{{trigger.body}}"
enabled: true
