---
pack: gluware
ref: gluware.nagios_trigger
name: nagios_trigger
uid: rule:gluware:nagios_trigger
tags: []
type:
  ref: standard
  parameters: {}
enabled: true
trigger:
  type: nagios.service_state_change
  ref: nagios.service_state_change
  description: Trigger type for nagios service state change event.
  parameters: {}
metadata_file: ''
context:
  user: st2admin
criteria:
  trigger.state:
    pattern: "^CRITICAL|DOWN|OK$"
    type: regex
  trigger.state_type:
    pattern: HARD
    type: eq
action:
  ref: silverwolf.get_device_state
  description: Checks NTP, OSPF, and BGP when a monitored interface goes down.
  parameters:
    host: "{{trigger.host}}"