---
pack: gluware
ref: gluware.nagios_trigger
name: run_routing_nsa
uid: rule:gluware:nagios_trigger
tags: []
type:
  ref: standard
  parameters: {}
enabled: true
trigger:
  type: nagios.service_state_change
  ref: nagios.service_state_change
  description: Trigger type for nagios service state change event.
  parameters: {}
metadata_file: ''
context:
  user: st2admin
criteria:
  trigger.state:
    pattern: "^CRITICAL|DOWN$"
    type: regex
  trigger.state_type:
    pattern: HARD
    type: eq
action:
  ref: gluware.run_routing_nsa_workflow
  description: Checks OSPF and BGP and interfaces when a monitored interface goes down.
  parameters:
    device_name: "{{trigger.host}}"
