---
name: "run_osv_nc_report_webhook"
pack: "gluware"
description: "Runs an OS Version non-compliance report on demand via a webhook."
enabled: true
trigger:
  type: "core.st2.webhook"
  parameters:
    url: "osv_nc_report" 
criteria: {}
action:
  ref: "gluware.run_os_compliance_report"
