---
name: "os_compliance_report"
pack: "gluware"
description: "Runs an OS Version non-compliance report at a give time."
enabled: true
trigger:
  type: "core.st2.CronTimer"
  parameters:
    minute: "30"
    hour: "01"
    day: "*"
criteria: {}
action:
  ref: "gluware.run_os_compliance_report"
