---
name: "sch_os_compliance_report"
pack: "gluware"
description: "Schedules an OS Version non-compliance report using st2 cron."
enabled: true
trigger:
  type: "core.st2.CronTimer"
  parameters:
    minute: "30"
    hour: "01"
    day: "*"
criteria: {}
action:
  ref: "gluware.run_os_compliance_report"
